# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dabanya02/Projects/joetracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dabanya02/Projects/joetracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dabanya02/Projects/joetracer/CMakeFiles /home/dabanya02/Projects/joetracer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dabanya02/Projects/joetracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named joetracer

# Build rule for target.
joetracer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joetracer
.PHONY : joetracer

# fast build rule for target.
joetracer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/build
.PHONY : joetracer/fast

include/imgui/backends/imgui_impl_sdl.o: include/imgui/backends/imgui_impl_sdl.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdl.o

# target to build an object file
include/imgui/backends/imgui_impl_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/backends/imgui_impl_sdl.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdl.cpp.o

include/imgui/backends/imgui_impl_sdl.i: include/imgui/backends/imgui_impl_sdl.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdl.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/backends/imgui_impl_sdl.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdl.cpp.i

include/imgui/backends/imgui_impl_sdl.s: include/imgui/backends/imgui_impl_sdl.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdl.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/backends/imgui_impl_sdl.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdl.cpp.s

include/imgui/backends/imgui_impl_sdlrenderer.o: include/imgui/backends/imgui_impl_sdlrenderer.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdlrenderer.o

# target to build an object file
include/imgui/backends/imgui_impl_sdlrenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/backends/imgui_impl_sdlrenderer.cpp.o
.PHONY : include/imgui/backends/imgui_impl_sdlrenderer.cpp.o

include/imgui/backends/imgui_impl_sdlrenderer.i: include/imgui/backends/imgui_impl_sdlrenderer.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdlrenderer.i

# target to preprocess a source file
include/imgui/backends/imgui_impl_sdlrenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/backends/imgui_impl_sdlrenderer.cpp.i
.PHONY : include/imgui/backends/imgui_impl_sdlrenderer.cpp.i

include/imgui/backends/imgui_impl_sdlrenderer.s: include/imgui/backends/imgui_impl_sdlrenderer.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdlrenderer.s

# target to generate assembly for a file
include/imgui/backends/imgui_impl_sdlrenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/backends/imgui_impl_sdlrenderer.cpp.s
.PHONY : include/imgui/backends/imgui_impl_sdlrenderer.cpp.s

include/imgui/imgui.o: include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.o

# target to build an object file
include/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui.cpp.o
.PHONY : include/imgui/imgui.cpp.o

include/imgui/imgui.i: include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.i

# target to preprocess a source file
include/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui.cpp.i
.PHONY : include/imgui/imgui.cpp.i

include/imgui/imgui.s: include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.s

# target to generate assembly for a file
include/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui.cpp.s
.PHONY : include/imgui/imgui.cpp.s

include/imgui/imgui_demo.o: include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.o

# target to build an object file
include/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_demo.cpp.o
.PHONY : include/imgui/imgui_demo.cpp.o

include/imgui/imgui_demo.i: include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.i

# target to preprocess a source file
include/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_demo.cpp.i
.PHONY : include/imgui/imgui_demo.cpp.i

include/imgui/imgui_demo.s: include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.s

# target to generate assembly for a file
include/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_demo.cpp.s
.PHONY : include/imgui/imgui_demo.cpp.s

include/imgui/imgui_draw.o: include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.o

# target to build an object file
include/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_draw.cpp.o
.PHONY : include/imgui/imgui_draw.cpp.o

include/imgui/imgui_draw.i: include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.i

# target to preprocess a source file
include/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_draw.cpp.i
.PHONY : include/imgui/imgui_draw.cpp.i

include/imgui/imgui_draw.s: include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.s

# target to generate assembly for a file
include/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_draw.cpp.s
.PHONY : include/imgui/imgui_draw.cpp.s

include/imgui/imgui_tables.o: include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.o

# target to build an object file
include/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_tables.cpp.o
.PHONY : include/imgui/imgui_tables.cpp.o

include/imgui/imgui_tables.i: include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.i

# target to preprocess a source file
include/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_tables.cpp.i
.PHONY : include/imgui/imgui_tables.cpp.i

include/imgui/imgui_tables.s: include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.s

# target to generate assembly for a file
include/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_tables.cpp.s
.PHONY : include/imgui/imgui_tables.cpp.s

include/imgui/imgui_widgets.o: include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.o

# target to build an object file
include/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_widgets.cpp.o
.PHONY : include/imgui/imgui_widgets.cpp.o

include/imgui/imgui_widgets.i: include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.i

# target to preprocess a source file
include/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_widgets.cpp.i
.PHONY : include/imgui/imgui_widgets.cpp.i

include/imgui/imgui_widgets.s: include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.s

# target to generate assembly for a file
include/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/include/imgui/imgui_widgets.cpp.s
.PHONY : include/imgui/imgui_widgets.cpp.s

src/BVHNode.o: src/BVHNode.cpp.o
.PHONY : src/BVHNode.o

# target to build an object file
src/BVHNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/BVHNode.cpp.o
.PHONY : src/BVHNode.cpp.o

src/BVHNode.i: src/BVHNode.cpp.i
.PHONY : src/BVHNode.i

# target to preprocess a source file
src/BVHNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/BVHNode.cpp.i
.PHONY : src/BVHNode.cpp.i

src/BVHNode.s: src/BVHNode.cpp.s
.PHONY : src/BVHNode.s

# target to generate assembly for a file
src/BVHNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/BVHNode.cpp.s
.PHONY : src/BVHNode.cpp.s

src/ConstantMedium.o: src/ConstantMedium.cpp.o
.PHONY : src/ConstantMedium.o

# target to build an object file
src/ConstantMedium.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/ConstantMedium.cpp.o
.PHONY : src/ConstantMedium.cpp.o

src/ConstantMedium.i: src/ConstantMedium.cpp.i
.PHONY : src/ConstantMedium.i

# target to preprocess a source file
src/ConstantMedium.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/ConstantMedium.cpp.i
.PHONY : src/ConstantMedium.cpp.i

src/ConstantMedium.s: src/ConstantMedium.cpp.s
.PHONY : src/ConstantMedium.s

# target to generate assembly for a file
src/ConstantMedium.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/ConstantMedium.cpp.s
.PHONY : src/ConstantMedium.cpp.s

src/Functions.o: src/Functions.cpp.o
.PHONY : src/Functions.o

# target to build an object file
src/Functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Functions.cpp.o
.PHONY : src/Functions.cpp.o

src/Functions.i: src/Functions.cpp.i
.PHONY : src/Functions.i

# target to preprocess a source file
src/Functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Functions.cpp.i
.PHONY : src/Functions.cpp.i

src/Functions.s: src/Functions.cpp.s
.PHONY : src/Functions.s

# target to generate assembly for a file
src/Functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Functions.cpp.s
.PHONY : src/Functions.cpp.s

src/Light.o: src/Light.cpp.o
.PHONY : src/Light.o

# target to build an object file
src/Light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Light.cpp.o
.PHONY : src/Light.cpp.o

src/Light.i: src/Light.cpp.i
.PHONY : src/Light.i

# target to preprocess a source file
src/Light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Light.cpp.i
.PHONY : src/Light.cpp.i

src/Light.s: src/Light.cpp.s
.PHONY : src/Light.s

# target to generate assembly for a file
src/Light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Light.cpp.s
.PHONY : src/Light.cpp.s

src/Move.o: src/Move.cpp.o
.PHONY : src/Move.o

# target to build an object file
src/Move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Move.cpp.o
.PHONY : src/Move.cpp.o

src/Move.i: src/Move.cpp.i
.PHONY : src/Move.i

# target to preprocess a source file
src/Move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Move.cpp.i
.PHONY : src/Move.cpp.i

src/Move.s: src/Move.cpp.s
.PHONY : src/Move.s

# target to generate assembly for a file
src/Move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Move.cpp.s
.PHONY : src/Move.cpp.s

src/PinholeCamera.o: src/PinholeCamera.cpp.o
.PHONY : src/PinholeCamera.o

# target to build an object file
src/PinholeCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/PinholeCamera.cpp.o
.PHONY : src/PinholeCamera.cpp.o

src/PinholeCamera.i: src/PinholeCamera.cpp.i
.PHONY : src/PinholeCamera.i

# target to preprocess a source file
src/PinholeCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/PinholeCamera.cpp.i
.PHONY : src/PinholeCamera.cpp.i

src/PinholeCamera.s: src/PinholeCamera.cpp.s
.PHONY : src/PinholeCamera.s

# target to generate assembly for a file
src/PinholeCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/PinholeCamera.cpp.s
.PHONY : src/PinholeCamera.cpp.s

src/Point.o: src/Point.cpp.o
.PHONY : src/Point.o

# target to build an object file
src/Point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Point.cpp.o
.PHONY : src/Point.cpp.o

src/Point.i: src/Point.cpp.i
.PHONY : src/Point.i

# target to preprocess a source file
src/Point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Point.cpp.i
.PHONY : src/Point.cpp.i

src/Point.s: src/Point.cpp.s
.PHONY : src/Point.s

# target to generate assembly for a file
src/Point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Point.cpp.s
.PHONY : src/Point.cpp.s

src/RandomGenerator.o: src/RandomGenerator.cpp.o
.PHONY : src/RandomGenerator.o

# target to build an object file
src/RandomGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/RandomGenerator.cpp.o
.PHONY : src/RandomGenerator.cpp.o

src/RandomGenerator.i: src/RandomGenerator.cpp.i
.PHONY : src/RandomGenerator.i

# target to preprocess a source file
src/RandomGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/RandomGenerator.cpp.i
.PHONY : src/RandomGenerator.cpp.i

src/RandomGenerator.s: src/RandomGenerator.cpp.s
.PHONY : src/RandomGenerator.s

# target to generate assembly for a file
src/RandomGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/RandomGenerator.cpp.s
.PHONY : src/RandomGenerator.cpp.s

src/Ray.o: src/Ray.cpp.o
.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i
.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s
.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/Rotation.o: src/Rotation.cpp.o
.PHONY : src/Rotation.o

# target to build an object file
src/Rotation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Rotation.cpp.o
.PHONY : src/Rotation.cpp.o

src/Rotation.i: src/Rotation.cpp.i
.PHONY : src/Rotation.i

# target to preprocess a source file
src/Rotation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Rotation.cpp.i
.PHONY : src/Rotation.cpp.i

src/Rotation.s: src/Rotation.cpp.s
.PHONY : src/Rotation.s

# target to generate assembly for a file
src/Rotation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Rotation.cpp.s
.PHONY : src/Rotation.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Sphere.o: src/Sphere.cpp.o
.PHONY : src/Sphere.o

# target to build an object file
src/Sphere.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Sphere.cpp.o
.PHONY : src/Sphere.cpp.o

src/Sphere.i: src/Sphere.cpp.i
.PHONY : src/Sphere.i

# target to preprocess a source file
src/Sphere.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Sphere.cpp.i
.PHONY : src/Sphere.cpp.i

src/Sphere.s: src/Sphere.cpp.s
.PHONY : src/Sphere.s

# target to generate assembly for a file
src/Sphere.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Sphere.cpp.s
.PHONY : src/Sphere.cpp.s

src/Translate.o: src/Translate.cpp.o
.PHONY : src/Translate.o

# target to build an object file
src/Translate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Translate.cpp.o
.PHONY : src/Translate.cpp.o

src/Translate.i: src/Translate.cpp.i
.PHONY : src/Translate.i

# target to preprocess a source file
src/Translate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Translate.cpp.i
.PHONY : src/Translate.cpp.i

src/Translate.s: src/Translate.cpp.s
.PHONY : src/Translate.s

# target to generate assembly for a file
src/Translate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Translate.cpp.s
.PHONY : src/Translate.cpp.s

src/Vec.o: src/Vec.cpp.o
.PHONY : src/Vec.o

# target to build an object file
src/Vec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Vec.cpp.o
.PHONY : src/Vec.cpp.o

src/Vec.i: src/Vec.cpp.i
.PHONY : src/Vec.i

# target to preprocess a source file
src/Vec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Vec.cpp.i
.PHONY : src/Vec.cpp.i

src/Vec.s: src/Vec.cpp.s
.PHONY : src/Vec.s

# target to generate assembly for a file
src/Vec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/Vec.cpp.s
.PHONY : src/Vec.cpp.s

src/aaBox.o: src/aaBox.cpp.o
.PHONY : src/aaBox.o

# target to build an object file
src/aaBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aaBox.cpp.o
.PHONY : src/aaBox.cpp.o

src/aaBox.i: src/aaBox.cpp.i
.PHONY : src/aaBox.i

# target to preprocess a source file
src/aaBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aaBox.cpp.i
.PHONY : src/aaBox.cpp.i

src/aaBox.s: src/aaBox.cpp.s
.PHONY : src/aaBox.s

# target to generate assembly for a file
src/aaBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aaBox.cpp.s
.PHONY : src/aaBox.cpp.s

src/aaRect.o: src/aaRect.cpp.o
.PHONY : src/aaRect.o

# target to build an object file
src/aaRect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aaRect.cpp.o
.PHONY : src/aaRect.cpp.o

src/aaRect.i: src/aaRect.cpp.i
.PHONY : src/aaRect.i

# target to preprocess a source file
src/aaRect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aaRect.cpp.i
.PHONY : src/aaRect.cpp.i

src/aaRect.s: src/aaRect.cpp.s
.PHONY : src/aaRect.s

# target to generate assembly for a file
src/aaRect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aaRect.cpp.s
.PHONY : src/aaRect.cpp.s

src/aabb.o: src/aabb.cpp.o
.PHONY : src/aabb.o

# target to build an object file
src/aabb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aabb.cpp.o
.PHONY : src/aabb.cpp.o

src/aabb.i: src/aabb.cpp.i
.PHONY : src/aabb.i

# target to preprocess a source file
src/aabb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aabb.cpp.i
.PHONY : src/aabb.cpp.i

src/aabb.s: src/aabb.cpp.s
.PHONY : src/aabb.s

# target to generate assembly for a file
src/aabb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/aabb.cpp.s
.PHONY : src/aabb.cpp.s

src/onb.o: src/onb.cpp.o
.PHONY : src/onb.o

# target to build an object file
src/onb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/onb.cpp.o
.PHONY : src/onb.cpp.o

src/onb.i: src/onb.cpp.i
.PHONY : src/onb.i

# target to preprocess a source file
src/onb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/onb.cpp.i
.PHONY : src/onb.cpp.i

src/onb.s: src/onb.cpp.s
.PHONY : src/onb.s

# target to generate assembly for a file
src/onb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/onb.cpp.s
.PHONY : src/onb.cpp.s

src/sdl.o: src/sdl.cpp.o
.PHONY : src/sdl.o

# target to build an object file
src/sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/sdl.cpp.o
.PHONY : src/sdl.cpp.o

src/sdl.i: src/sdl.cpp.i
.PHONY : src/sdl.i

# target to preprocess a source file
src/sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/sdl.cpp.i
.PHONY : src/sdl.cpp.i

src/sdl.s: src/sdl.cpp.s
.PHONY : src/sdl.s

# target to generate assembly for a file
src/sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/joetracer.dir/build.make CMakeFiles/joetracer.dir/src/sdl.cpp.s
.PHONY : src/sdl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... joetracer"
	@echo "... include/imgui/backends/imgui_impl_sdl.o"
	@echo "... include/imgui/backends/imgui_impl_sdl.i"
	@echo "... include/imgui/backends/imgui_impl_sdl.s"
	@echo "... include/imgui/backends/imgui_impl_sdlrenderer.o"
	@echo "... include/imgui/backends/imgui_impl_sdlrenderer.i"
	@echo "... include/imgui/backends/imgui_impl_sdlrenderer.s"
	@echo "... include/imgui/imgui.o"
	@echo "... include/imgui/imgui.i"
	@echo "... include/imgui/imgui.s"
	@echo "... include/imgui/imgui_demo.o"
	@echo "... include/imgui/imgui_demo.i"
	@echo "... include/imgui/imgui_demo.s"
	@echo "... include/imgui/imgui_draw.o"
	@echo "... include/imgui/imgui_draw.i"
	@echo "... include/imgui/imgui_draw.s"
	@echo "... include/imgui/imgui_tables.o"
	@echo "... include/imgui/imgui_tables.i"
	@echo "... include/imgui/imgui_tables.s"
	@echo "... include/imgui/imgui_widgets.o"
	@echo "... include/imgui/imgui_widgets.i"
	@echo "... include/imgui/imgui_widgets.s"
	@echo "... src/BVHNode.o"
	@echo "... src/BVHNode.i"
	@echo "... src/BVHNode.s"
	@echo "... src/ConstantMedium.o"
	@echo "... src/ConstantMedium.i"
	@echo "... src/ConstantMedium.s"
	@echo "... src/Functions.o"
	@echo "... src/Functions.i"
	@echo "... src/Functions.s"
	@echo "... src/Light.o"
	@echo "... src/Light.i"
	@echo "... src/Light.s"
	@echo "... src/Move.o"
	@echo "... src/Move.i"
	@echo "... src/Move.s"
	@echo "... src/PinholeCamera.o"
	@echo "... src/PinholeCamera.i"
	@echo "... src/PinholeCamera.s"
	@echo "... src/Point.o"
	@echo "... src/Point.i"
	@echo "... src/Point.s"
	@echo "... src/RandomGenerator.o"
	@echo "... src/RandomGenerator.i"
	@echo "... src/RandomGenerator.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/Rotation.o"
	@echo "... src/Rotation.i"
	@echo "... src/Rotation.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Sphere.o"
	@echo "... src/Sphere.i"
	@echo "... src/Sphere.s"
	@echo "... src/Translate.o"
	@echo "... src/Translate.i"
	@echo "... src/Translate.s"
	@echo "... src/Vec.o"
	@echo "... src/Vec.i"
	@echo "... src/Vec.s"
	@echo "... src/aaBox.o"
	@echo "... src/aaBox.i"
	@echo "... src/aaBox.s"
	@echo "... src/aaRect.o"
	@echo "... src/aaRect.i"
	@echo "... src/aaRect.s"
	@echo "... src/aabb.o"
	@echo "... src/aabb.i"
	@echo "... src/aabb.s"
	@echo "... src/onb.o"
	@echo "... src/onb.i"
	@echo "... src/onb.s"
	@echo "... src/sdl.o"
	@echo "... src/sdl.i"
	@echo "... src/sdl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

