#ifndef _COSINEONB_PDF
#define _COSINEONB_PDF

#include "../onb.h"
#include "../pdf.h"
// A cosine PDF with the normal based on the orthonormal basis generated by w.
class CosineONB_PDF : public pdf {
public:
  CosineONB_PDF(const Vector3 &w) { uvw.buildFromW(w); }

  // Returns the value of a ray inputted into a cosine PDF centered on the ONB coordinates. Returns zero if the ray is absorbed, i.e. the ray goes into the object.
  virtual double value(const Vector3 &direction) const override {
    Vector3 normalizedDir = direction.normalized();
    float cosine = normalizedDir.dot(uvw.w());
    return (cosine < 0.0)? 0 : cosine / PI;
  }

  // Returns a ray generated from a cosine PDF using the ONB coordinates.
  virtual Vector3 generate() const override {
    return uvw.local(randomCosinePDFRay());
  }

  onb uvw;
};

#endif
